######## VARIABLES ########
variables:
  BUILD_CONFIGURATION: "Release"
  COVERAGE_REPORT_PATH: "Couverture/coverage.opencover.xml"
  NUGET_PACKAGES_DIRECTORY: ".nuget/packages"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"

default:
  tags:
    - gitlab-lamboft-docker-runner

######## CACHE ########
cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - "$NUGET_PACKAGES_DIRECTORY"

######## STAGES ########
stages:
  - pre-treatment
  - build
  - test
  - scan-vulnerabilities
  - sonar-build-and-analysis
  - deploy
#   - cleanup

# ######## PRE-TREATMENT ########
pre-treatment:
  stage: pre-treatment
  tags:
    - gitlab-lamboft-docker-runner
  script:
    - echo "Nettoyage des caches NuGet"
    - dotnet nuget locals all --clear # Nettoie les caches locaux NuGet
    - echo "Nettoyage des fichiers intermédiaires"
    - find . -name "*.dll" -o -name "*.pdb" -o -name "*.tmp" -o -name "*.md"| xargs rm -rf
    - echo "Nettoyage des artefacts de build"
    - rm -rf **/bin/ **/obj/ # Nettoie les binaires et les objets
    - echo "Nettoyage des artefacts de test"
    - rm -rf **/TestResults/ # Nettoie les résultats de tests
    - echo "Nettoyage des artefacts de couverture"
    - rm -rf Couverture/ # Nettoie les résultats de couverture
    - echo "Récupération des fichiers de solution et dossier de Test"
  artifacts:
    paths:
      - "**/bin/**" # Artéfacts de build si nécessaire
    expire_in: 20 minutes

# ######## BUILD ########
build:
  stage: build
  script:
    - SOLUTION_FILE=$(ls *.sln)
    - echo "Compilation des projets à partir de $SOLUTION_FILE"
    - dotnet build $SOLUTION_FILE --configuration $BUILD_CONFIGURATION
    - PROJECT=$(ls *.sln | sed -E 's/\.sln$//')
    - chmod -R 750 $PROJECT/bin/ # bonne pratiques pour la securité on restreint l'accès aux binaires
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - "$NUGET_PACKAGES_DIRECTORY"
  artifacts:
    paths:
      - "**/bin/**" # Artéfacts de build si nécessaire
    expire_in: 20 minutes

# ######## TEST ########
test:
  stage: test
  tags:
    - gitlab-lamboft-docker-runner
  script:
    - echo "Exécution des tests unitaires avec collecte de couverture"
    - dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.21
    - export PATH="$PATH:$HOME/.dotnet/tools"
    - TEST_PROJECT=$(ls | grep -P -o '\w+\.Tests$'  | head -n 1) # Récupère le premier dossier se terminant par .Tests
    - echo "Lancement des tests unitaires"
    - |
      dotnet test $TEST_PROJECT/$TEST_PROJECT.csproj \
        --configuration $BUILD_CONFIGURATION \
        --collect:"XPlat Code Coverage" \
        /p:CollectCoverage=true \
        /p:CoverletOutput=../Couverture/ \
        /p:CoverletOutputFormat="opencover"
  artifacts:
    when: always
    paths:
      - $COVERAGE_REPORT_PATH
    reports:
      junit: $COVERAGE_REPORT_PATH

before_script:
  - export $(cat .env | xargs)

###### TRIVY FS VULNERABILITIES #####
scan-vulnerabilities:
  stage: scan-vulnerabilities
  tags:
    - gitlab-lamboft-shell-develop
  script:
    - dotnet list package --vulnerable
    - chmod +x trivy.sh
    - ./trivy.sh
  allow_failure: true

######## SONARQUBE BUILD AND ANALYSIS ########
sonar-build-and-analysis:
  stage: sonar-build-and-analysis
  tags:
    - gitlab-lamboft-shell-develop
  variables:
    RUNNER_TAG: "development"
    allow_failure: false
  script:
    - echo "Lancement de l'analyse SonarQube."
    - chmod +x sonar_check.sh; ./sonar_check.sh
    - echo "Génération du rapport SonarQube."
    - chmod +x sonar_report.sh; ./sonar_report.sh
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  dependencies:
    - test # Dépend de la phase test 

# ######## DOCKER BUILD AND TRIVY ANALYSIS ########
# ######## DEPLOY ENV DEV ########
Env_dev:
  stage: deploy
  tags:
    - gitlab-lamboft-shell-develop
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  variables:
    RUNNER_TAG: "development"
    allow_failure: false
  script:
    - echo "DEVELOPMENT_TAG=$DEVELOPMENT_TAG" >> build.env
    - |
      if [[ "$DEVELOPMENT_TAG" == "true" ]]; then
        echo "Déploiement en environnement de développement"
        echo "Construction de l'image Docker"
        tag=$(./image_tag.sh | tr -cd '0-9.')
        echo "DOCKER_TAG=$tag" > .env.ci
        CERT_PASSWORD="lambo"
        echo "CERT_PASSWORD=$CERT_PASSWORD" >> .env.ci
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag .
        echo "Scan de l'image Docker avec Trivy"
        trivy image --exit-code 0 --severity HIGH,CRITICAL $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
        echo "Scan de l'image Docker terminé"
        docker push  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
        echo "Déploiement de l'image Docker"
        docker rm -f dev-$CI_PROJECT_NAME || true
        docker-compose -f application-compose.yml --env-file .env.ci up -d
        if [ $? != 0 ]; then
          echo "Echec de lancement du conatiner docker."
          ./docker_cleanup.sh dev-$CI_PROJECT_NAME
          exit 1
        fi
      else
        echo "No environment tag set for this runner development"
        exit 1
      fi

  artifacts:
    reports:
      dotenv: build.env
    paths:
      - .docker_tag
    expire_in: 1 day

# ######## DEPLOY ENV STAGING #########
Env_staging:
  stage: deploy
  tags:
    - gitlab-lamboft-shell-runner
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    RUNNER_TAG: "staging"
    allow_failure: false
  script:
    - echo "STAGING_TAG=$STAGING_TAG" >> build.env
    - |
      if [[ "$STAGING_TAG" == "true" ]]; then
        echo "Déploiement en environnement de staging"
        echo "Construction de l'image Docker"
        dotnet nuget locals all --clear
        tag=$(./image_tag.sh | tr -cd '0-9.')
        echo "DOCKER_TAG=$tag" > .env.ci 
        echo "CERT_PASSWORD=$CERT_PASSWORD" >> .env.ci
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag .
        docker push  $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$tag
        echo "Déploiement de l'image Docker"
        docker rm -f staging-$CI_PROJECT_NAME || true
        docker-compose -f application-compose.yml --env-file .env.ci up -d
        if [ $? != 0 ]; then
          echo "Echec de lancement du conatiner docker."
          ./docker_cleanup.sh staging-$CI_PROJECT_NAME
          exit 1
        fi
        docker network connect redis_redis staging-$CI_PROJECT_NAME
      else
        echo "No environment tag set for this runner development"
        exit 1
      fi
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - .docker_tag
    expire_in: 1 day
# ######## CLEANUP ########
# cleanup:
#   stage: cleanup
#   tags:
#     - gitlab-lamboft-shell-runner
#   script:
#     - echo "Nettoyage du repertoire de travail"
